service: serverless-s3-go

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::*"

custom:
  defaultStage: dev

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: func
          method: post
          cors: true

#functions:
#  create:
#    handler: bin/create
#    events:
#      - s3:
#        bucket: gakustestbuckets
#        event: s3:ObjectCreated:*

resources:
  Resources:
    resize:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: gakustestbuckets2
